# this.create("/", ["ADMIN", "PREM"], create);
#     this.read("/", ["PUBLIC"], read);
#     this.read("/:eid", ["PUBLIC"], readOne);
#     this.update("/:eid", ["ADMIN", "PREM"], update);
#     this.destroy("/:eid", ["ADMIN", "PREM"], destroy);
components:
  schemas:
    Register:
      type: object
      properties:
        title: string
        price: number
        photo: string
        stock: number
      example:
        title: "title"
        price: 100
        photo: "https://random.responsiveimages.io/300/300"
        stock: 10
  response:
    success:
      type: object
      properties:
        status:
          type: string
          example: Successful Code
        payload:
          type: string
          properties:
            _id: string
            title: string
            price: number
            photo: string
            stock: number
            createdAt: string
            updatedAt: string
          example:
            status: success
            payload:
              _id: 123
              title: "title"
              price: 100
              photo: "https://random.responsiveimages.io/300/300"
              stock: 10
              createdAt: "2020-01-01T00:00:00.000Z"
              updatedAt: "2020-01-01T00:00:00.000Z"

  paths:
    api/products/:
      post:
        summary: Register a new product
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
        responses:
          201:
            description: User created
            content:
              application/json:
                schema:
                  $ref: '#/components/response/success'
      get:
        summary: Get all products
        responses:
          201:
            description: Get all products
            content:
              application/json:
                schema:
                  $ref: '#/components/response/success'
    api/products/:pid:
      put:
        summary: Update a product
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
        responses:
          201:
            description: Update a product
            content:
              application/json:
                schema:
                  $ref: '#/components/response/success'
      delete:
        summary: Delete a product
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
        responses:
          201:
            description: Delete a product
            content:
              application/json:
                schema:
                  $ref: '#/components/response/success'
  